### ISSUE TITLE
When the portal disabled, the balance doesn't become 0

### ISSUE THREAD

**Issue by sky4009** [conflux-fans/pos-pool#19]
Reproduce steps:
1. Connect to the Portal with testnet
2. Select a pool and Stack some CFX in it
3. Wait for there are some rewards generated
4. Disable the portal and refresh the page

Expect:
All the number related to the wallet should become 0
Actual:
The Balance is not, it is 659.56920

**Comment by SSSensational** [comment]
There is a bug in the code: Continues to poll the empty address for the balance after closing the Portal, and the return result is 659.56920.
I have fixed in this PR #21 .
